/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalTrainingRouteImport } from './routes/technical-training'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollaborationsConsultancyRouteImport } from './routes/collaborations-consultancy'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AcademicActivitiesRouteImport } from './routes/academic-activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordIdRouteImport } from './routes/record.$id'
import { Route as LegacyWorkshopsRouteImport } from './routes/legacy/workshops'
import { Route as LegacyTalksRouteImport } from './routes/legacy/talks'
import { Route as LegacyResearchSupervisionRouteImport } from './routes/legacy/research-supervision'
import { Route as LegacyPgRouteImport } from './routes/legacy/pg'
import { Route as LegacyBosRouteImport } from './routes/legacy/bos'

const TechnicalTrainingRoute = TechnicalTrainingRouteImport.update({
  id: '/technical-training',
  path: '/technical-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsConsultancyRoute =
  CollaborationsConsultancyRouteImport.update({
    id: '/collaborations-consultancy',
    path: '/collaborations-consultancy',
    getParentRoute: () => rootRouteImport,
  } as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicActivitiesRoute = AcademicActivitiesRouteImport.update({
  id: '/academic-activities',
  path: '/academic-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIdRoute = RecordIdRouteImport.update({
  id: '/record/$id',
  path: '/record/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyWorkshopsRoute = LegacyWorkshopsRouteImport.update({
  id: '/legacy/workshops',
  path: '/legacy/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyTalksRoute = LegacyTalksRouteImport.update({
  id: '/legacy/talks',
  path: '/legacy/talks',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyResearchSupervisionRoute =
  LegacyResearchSupervisionRouteImport.update({
    id: '/legacy/research-supervision',
    path: '/legacy/research-supervision',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegacyPgRoute = LegacyPgRouteImport.update({
  id: '/legacy/pg',
  path: '/legacy/pg',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyBosRoute = LegacyBosRouteImport.update({
  id: '/legacy/bos',
  path: '/legacy/bos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-activities': typeof AcademicActivitiesRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/awards': typeof AwardsRoute
  '/collaborations-consultancy': typeof CollaborationsConsultancyRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/legacy/bos': typeof LegacyBosRoute
  '/legacy/pg': typeof LegacyPgRoute
  '/legacy/research-supervision': typeof LegacyResearchSupervisionRoute
  '/legacy/talks': typeof LegacyTalksRoute
  '/legacy/workshops': typeof LegacyWorkshopsRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-activities': typeof AcademicActivitiesRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/awards': typeof AwardsRoute
  '/collaborations-consultancy': typeof CollaborationsConsultancyRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/legacy/bos': typeof LegacyBosRoute
  '/legacy/pg': typeof LegacyPgRoute
  '/legacy/research-supervision': typeof LegacyResearchSupervisionRoute
  '/legacy/talks': typeof LegacyTalksRoute
  '/legacy/workshops': typeof LegacyWorkshopsRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-activities': typeof AcademicActivitiesRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/awards': typeof AwardsRoute
  '/collaborations-consultancy': typeof CollaborationsConsultancyRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/legacy/bos': typeof LegacyBosRoute
  '/legacy/pg': typeof LegacyPgRoute
  '/legacy/research-supervision': typeof LegacyResearchSupervisionRoute
  '/legacy/talks': typeof LegacyTalksRoute
  '/legacy/workshops': typeof LegacyWorkshopsRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-activities'
    | '/access-denied'
    | '/admin'
    | '/awards'
    | '/collaborations-consultancy'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/people'
    | '/publications'
    | '/research'
    | '/reset-password'
    | '/technical-training'
    | '/legacy/bos'
    | '/legacy/pg'
    | '/legacy/research-supervision'
    | '/legacy/talks'
    | '/legacy/workshops'
    | '/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-activities'
    | '/access-denied'
    | '/admin'
    | '/awards'
    | '/collaborations-consultancy'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/people'
    | '/publications'
    | '/research'
    | '/reset-password'
    | '/technical-training'
    | '/legacy/bos'
    | '/legacy/pg'
    | '/legacy/research-supervision'
    | '/legacy/talks'
    | '/legacy/workshops'
    | '/record/$id'
  id:
    | '__root__'
    | '/'
    | '/academic-activities'
    | '/access-denied'
    | '/admin'
    | '/awards'
    | '/collaborations-consultancy'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/people'
    | '/publications'
    | '/research'
    | '/reset-password'
    | '/technical-training'
    | '/legacy/bos'
    | '/legacy/pg'
    | '/legacy/research-supervision'
    | '/legacy/talks'
    | '/legacy/workshops'
    | '/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicActivitiesRoute: typeof AcademicActivitiesRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRoute
  AwardsRoute: typeof AwardsRoute
  CollaborationsConsultancyRoute: typeof CollaborationsConsultancyRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  PeopleRoute: typeof PeopleRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TechnicalTrainingRoute: typeof TechnicalTrainingRoute
  LegacyBosRoute: typeof LegacyBosRoute
  LegacyPgRoute: typeof LegacyPgRoute
  LegacyResearchSupervisionRoute: typeof LegacyResearchSupervisionRoute
  LegacyTalksRoute: typeof LegacyTalksRoute
  LegacyWorkshopsRoute: typeof LegacyWorkshopsRoute
  RecordIdRoute: typeof RecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical-training': {
      id: '/technical-training'
      path: '/technical-training'
      fullPath: '/technical-training'
      preLoaderRoute: typeof TechnicalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations-consultancy': {
      id: '/collaborations-consultancy'
      path: '/collaborations-consultancy'
      fullPath: '/collaborations-consultancy'
      preLoaderRoute: typeof CollaborationsConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-activities': {
      id: '/academic-activities'
      path: '/academic-activities'
      fullPath: '/academic-activities'
      preLoaderRoute: typeof AcademicActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$id': {
      id: '/record/$id'
      path: '/record/$id'
      fullPath: '/record/$id'
      preLoaderRoute: typeof RecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/workshops': {
      id: '/legacy/workshops'
      path: '/legacy/workshops'
      fullPath: '/legacy/workshops'
      preLoaderRoute: typeof LegacyWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/talks': {
      id: '/legacy/talks'
      path: '/legacy/talks'
      fullPath: '/legacy/talks'
      preLoaderRoute: typeof LegacyTalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/research-supervision': {
      id: '/legacy/research-supervision'
      path: '/legacy/research-supervision'
      fullPath: '/legacy/research-supervision'
      preLoaderRoute: typeof LegacyResearchSupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/pg': {
      id: '/legacy/pg'
      path: '/legacy/pg'
      fullPath: '/legacy/pg'
      preLoaderRoute: typeof LegacyPgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/bos': {
      id: '/legacy/bos'
      path: '/legacy/bos'
      fullPath: '/legacy/bos'
      preLoaderRoute: typeof LegacyBosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicActivitiesRoute: AcademicActivitiesRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRoute,
  AwardsRoute: AwardsRoute,
  CollaborationsConsultancyRoute: CollaborationsConsultancyRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  PeopleRoute: PeopleRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TechnicalTrainingRoute: TechnicalTrainingRoute,
  LegacyBosRoute: LegacyBosRoute,
  LegacyPgRoute: LegacyPgRoute,
  LegacyResearchSupervisionRoute: LegacyResearchSupervisionRoute,
  LegacyTalksRoute: LegacyTalksRoute,
  LegacyWorkshopsRoute: LegacyWorkshopsRoute,
  RecordIdRoute: RecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
