/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalTrainingRouteImport } from './routes/technical-training'
import { Route as Research_oldRouteImport } from './routes/research_old'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as Index_oldRouteImport } from './routes/index_old'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollaborationsConsultancyRouteImport } from './routes/collaborations-consultancy'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as Admin_utf8RouteImport } from './routes/admin_utf8'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademicActivitiesRouteImport } from './routes/academic-activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordIdRouteImport } from './routes/record.$id'
import { Route as LegacyWorkshopsRouteImport } from './routes/legacy/workshops'
import { Route as LegacyTalksRouteImport } from './routes/legacy/talks'
import { Route as LegacyResearchSupervisionRouteImport } from './routes/legacy/research-supervision'
import { Route as LegacyPgRouteImport } from './routes/legacy/pg'
import { Route as LegacyFieldActivitiesRouteImport } from './routes/legacy/field-activities'
import { Route as LegacyFacilitiesRouteImport } from './routes/legacy/facilities'
import { Route as LegacyBosRouteImport } from './routes/legacy/bos'
import { Route as LegacyAboutRouteImport } from './routes/legacy/about'

const TechnicalTrainingRoute = TechnicalTrainingRouteImport.update({
  id: '/technical-training',
  path: '/technical-training',
  getParentRoute: () => rootRouteImport,
} as any)
const Research_oldRoute = Research_oldRouteImport.update({
  id: '/research_old',
  path: '/research_old',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const Index_oldRoute = Index_oldRouteImport.update({
  id: '/index_old',
  path: '/index_old',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsConsultancyRoute =
  CollaborationsConsultancyRouteImport.update({
    id: '/collaborations-consultancy',
    path: '/collaborations-consultancy',
    getParentRoute: () => rootRouteImport,
  } as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_utf8Route = Admin_utf8RouteImport.update({
  id: '/admin_utf8',
  path: '/admin_utf8',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicActivitiesRoute = AcademicActivitiesRouteImport.update({
  id: '/academic-activities',
  path: '/academic-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIdRoute = RecordIdRouteImport.update({
  id: '/record/$id',
  path: '/record/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyWorkshopsRoute = LegacyWorkshopsRouteImport.update({
  id: '/legacy/workshops',
  path: '/legacy/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyTalksRoute = LegacyTalksRouteImport.update({
  id: '/legacy/talks',
  path: '/legacy/talks',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyResearchSupervisionRoute =
  LegacyResearchSupervisionRouteImport.update({
    id: '/legacy/research-supervision',
    path: '/legacy/research-supervision',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegacyPgRoute = LegacyPgRouteImport.update({
  id: '/legacy/pg',
  path: '/legacy/pg',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyFieldActivitiesRoute = LegacyFieldActivitiesRouteImport.update({
  id: '/legacy/field-activities',
  path: '/legacy/field-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyFacilitiesRoute = LegacyFacilitiesRouteImport.update({
  id: '/legacy/facilities',
  path: '/legacy/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyBosRoute = LegacyBosRouteImport.update({
  id: '/legacy/bos',
  path: '/legacy/bos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyAboutRoute = LegacyAboutRouteImport.update({
  id: '/legacy/about',
  path: '/legacy/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-activities': typeof AcademicActivitiesRoute
  '/admin': typeof AdminRoute
  '/admin_utf8': typeof Admin_utf8Route
  '/awards': typeof AwardsRoute
  '/collaborations-consultancy': typeof CollaborationsConsultancyRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/index_old': typeof Index_oldRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/research_old': typeof Research_oldRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/legacy/about': typeof LegacyAboutRoute
  '/legacy/bos': typeof LegacyBosRoute
  '/legacy/facilities': typeof LegacyFacilitiesRoute
  '/legacy/field-activities': typeof LegacyFieldActivitiesRoute
  '/legacy/pg': typeof LegacyPgRoute
  '/legacy/research-supervision': typeof LegacyResearchSupervisionRoute
  '/legacy/talks': typeof LegacyTalksRoute
  '/legacy/workshops': typeof LegacyWorkshopsRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-activities': typeof AcademicActivitiesRoute
  '/admin': typeof AdminRoute
  '/admin_utf8': typeof Admin_utf8Route
  '/awards': typeof AwardsRoute
  '/collaborations-consultancy': typeof CollaborationsConsultancyRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/index_old': typeof Index_oldRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/research_old': typeof Research_oldRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/legacy/about': typeof LegacyAboutRoute
  '/legacy/bos': typeof LegacyBosRoute
  '/legacy/facilities': typeof LegacyFacilitiesRoute
  '/legacy/field-activities': typeof LegacyFieldActivitiesRoute
  '/legacy/pg': typeof LegacyPgRoute
  '/legacy/research-supervision': typeof LegacyResearchSupervisionRoute
  '/legacy/talks': typeof LegacyTalksRoute
  '/legacy/workshops': typeof LegacyWorkshopsRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-activities': typeof AcademicActivitiesRoute
  '/admin': typeof AdminRoute
  '/admin_utf8': typeof Admin_utf8Route
  '/awards': typeof AwardsRoute
  '/collaborations-consultancy': typeof CollaborationsConsultancyRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/index_old': typeof Index_oldRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/research_old': typeof Research_oldRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/legacy/about': typeof LegacyAboutRoute
  '/legacy/bos': typeof LegacyBosRoute
  '/legacy/facilities': typeof LegacyFacilitiesRoute
  '/legacy/field-activities': typeof LegacyFieldActivitiesRoute
  '/legacy/pg': typeof LegacyPgRoute
  '/legacy/research-supervision': typeof LegacyResearchSupervisionRoute
  '/legacy/talks': typeof LegacyTalksRoute
  '/legacy/workshops': typeof LegacyWorkshopsRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-activities'
    | '/admin'
    | '/admin_utf8'
    | '/awards'
    | '/collaborations-consultancy'
    | '/contact'
    | '/gallery'
    | '/index_old'
    | '/people'
    | '/publications'
    | '/research'
    | '/research_old'
    | '/technical-training'
    | '/legacy/about'
    | '/legacy/bos'
    | '/legacy/facilities'
    | '/legacy/field-activities'
    | '/legacy/pg'
    | '/legacy/research-supervision'
    | '/legacy/talks'
    | '/legacy/workshops'
    | '/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-activities'
    | '/admin'
    | '/admin_utf8'
    | '/awards'
    | '/collaborations-consultancy'
    | '/contact'
    | '/gallery'
    | '/index_old'
    | '/people'
    | '/publications'
    | '/research'
    | '/research_old'
    | '/technical-training'
    | '/legacy/about'
    | '/legacy/bos'
    | '/legacy/facilities'
    | '/legacy/field-activities'
    | '/legacy/pg'
    | '/legacy/research-supervision'
    | '/legacy/talks'
    | '/legacy/workshops'
    | '/record/$id'
  id:
    | '__root__'
    | '/'
    | '/academic-activities'
    | '/admin'
    | '/admin_utf8'
    | '/awards'
    | '/collaborations-consultancy'
    | '/contact'
    | '/gallery'
    | '/index_old'
    | '/people'
    | '/publications'
    | '/research'
    | '/research_old'
    | '/technical-training'
    | '/legacy/about'
    | '/legacy/bos'
    | '/legacy/facilities'
    | '/legacy/field-activities'
    | '/legacy/pg'
    | '/legacy/research-supervision'
    | '/legacy/talks'
    | '/legacy/workshops'
    | '/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicActivitiesRoute: typeof AcademicActivitiesRoute
  AdminRoute: typeof AdminRoute
  Admin_utf8Route: typeof Admin_utf8Route
  AwardsRoute: typeof AwardsRoute
  CollaborationsConsultancyRoute: typeof CollaborationsConsultancyRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  Index_oldRoute: typeof Index_oldRoute
  PeopleRoute: typeof PeopleRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  Research_oldRoute: typeof Research_oldRoute
  TechnicalTrainingRoute: typeof TechnicalTrainingRoute
  LegacyAboutRoute: typeof LegacyAboutRoute
  LegacyBosRoute: typeof LegacyBosRoute
  LegacyFacilitiesRoute: typeof LegacyFacilitiesRoute
  LegacyFieldActivitiesRoute: typeof LegacyFieldActivitiesRoute
  LegacyPgRoute: typeof LegacyPgRoute
  LegacyResearchSupervisionRoute: typeof LegacyResearchSupervisionRoute
  LegacyTalksRoute: typeof LegacyTalksRoute
  LegacyWorkshopsRoute: typeof LegacyWorkshopsRoute
  RecordIdRoute: typeof RecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical-training': {
      id: '/technical-training'
      path: '/technical-training'
      fullPath: '/technical-training'
      preLoaderRoute: typeof TechnicalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research_old': {
      id: '/research_old'
      path: '/research_old'
      fullPath: '/research_old'
      preLoaderRoute: typeof Research_oldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index_old': {
      id: '/index_old'
      path: '/index_old'
      fullPath: '/index_old'
      preLoaderRoute: typeof Index_oldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations-consultancy': {
      id: '/collaborations-consultancy'
      path: '/collaborations-consultancy'
      fullPath: '/collaborations-consultancy'
      preLoaderRoute: typeof CollaborationsConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_utf8': {
      id: '/admin_utf8'
      path: '/admin_utf8'
      fullPath: '/admin_utf8'
      preLoaderRoute: typeof Admin_utf8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-activities': {
      id: '/academic-activities'
      path: '/academic-activities'
      fullPath: '/academic-activities'
      preLoaderRoute: typeof AcademicActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$id': {
      id: '/record/$id'
      path: '/record/$id'
      fullPath: '/record/$id'
      preLoaderRoute: typeof RecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/workshops': {
      id: '/legacy/workshops'
      path: '/legacy/workshops'
      fullPath: '/legacy/workshops'
      preLoaderRoute: typeof LegacyWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/talks': {
      id: '/legacy/talks'
      path: '/legacy/talks'
      fullPath: '/legacy/talks'
      preLoaderRoute: typeof LegacyTalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/research-supervision': {
      id: '/legacy/research-supervision'
      path: '/legacy/research-supervision'
      fullPath: '/legacy/research-supervision'
      preLoaderRoute: typeof LegacyResearchSupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/pg': {
      id: '/legacy/pg'
      path: '/legacy/pg'
      fullPath: '/legacy/pg'
      preLoaderRoute: typeof LegacyPgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/field-activities': {
      id: '/legacy/field-activities'
      path: '/legacy/field-activities'
      fullPath: '/legacy/field-activities'
      preLoaderRoute: typeof LegacyFieldActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/facilities': {
      id: '/legacy/facilities'
      path: '/legacy/facilities'
      fullPath: '/legacy/facilities'
      preLoaderRoute: typeof LegacyFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/bos': {
      id: '/legacy/bos'
      path: '/legacy/bos'
      fullPath: '/legacy/bos'
      preLoaderRoute: typeof LegacyBosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/about': {
      id: '/legacy/about'
      path: '/legacy/about'
      fullPath: '/legacy/about'
      preLoaderRoute: typeof LegacyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicActivitiesRoute: AcademicActivitiesRoute,
  AdminRoute: AdminRoute,
  Admin_utf8Route: Admin_utf8Route,
  AwardsRoute: AwardsRoute,
  CollaborationsConsultancyRoute: CollaborationsConsultancyRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  Index_oldRoute: Index_oldRoute,
  PeopleRoute: PeopleRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  Research_oldRoute: Research_oldRoute,
  TechnicalTrainingRoute: TechnicalTrainingRoute,
  LegacyAboutRoute: LegacyAboutRoute,
  LegacyBosRoute: LegacyBosRoute,
  LegacyFacilitiesRoute: LegacyFacilitiesRoute,
  LegacyFieldActivitiesRoute: LegacyFieldActivitiesRoute,
  LegacyPgRoute: LegacyPgRoute,
  LegacyResearchSupervisionRoute: LegacyResearchSupervisionRoute,
  LegacyTalksRoute: LegacyTalksRoute,
  LegacyWorkshopsRoute: LegacyWorkshopsRoute,
  RecordIdRoute: RecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
